services:
  - type: web
    name: findland-africa-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements-minimal.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://findland-africa.vercel.app
    healthCheckPath: /health
    autoDeploy: true
