# Trivy Security Scanner Ignore File
# This file contains known vulnerabilities that are acceptable for this project

# Frontend Development Dependencies
# These are development-only dependencies and don't affect production
- id: CVE-2021-23369
  reason: "nth-check vulnerability in development dependencies only"
  
- id: CVE-2021-23368  
  reason: "css-select vulnerability in development dependencies only"
  
- id: CVE-2021-23367
  reason: "svgo vulnerability in development dependencies only"
  
- id: CVE-2021-23366
  reason: "@svgr/webpack vulnerability in development dependencies only"
  
- id: CVE-2021-23365
  reason: "react-scripts vulnerability in development dependencies only"
  
- id: CVE-2021-23364
  reason: "postcss vulnerability in development dependencies only"
  
- id: CVE-2021-23363
  reason: "webpack-dev-server vulnerability in development dependencies only"

# General ignore patterns for development dependencies
- id: "GHSA-*"
  reason: "Development dependency vulnerabilities that don't affect production"
